# Site settings
title: Know me
email: b1xbao2@hotmail.com
description: A Serious Learner
# > # this means to ignore newlines until "baseurl:"
#   Happy to see new things
##  research  travel
#   Serious to do things
##  project   host

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://seriouslearner.top" 
# twitter_username: jekyllrb
github_username:  huibuyudeyutou
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown

# highlight
# 本地用rouge, github上用pygments
# highlighter: pygments
# highlighter: rouge
# highlighter: false
